openapi: 3.0.0
info:
  title: BigBuy
  version: v202102
  description: OpenAPI spefication to interact with bigbuy.eu
servers:
  - url: 'https://api.bigbuy.eu'
    description: Production endpoint
  - url: 'https://api.sandbox.bigbuy.eu'
    description: Sandbox endpoint
paths:
  '/rest/catalog/categories/{id}.{_format}':
    # $ref: "./resources/catalog/categories/category-by-id.yaml" 
    get:
      summary: Your GET endpoint
      tags:
        - categories
      responses:
        '200':
          description: Returned when successful
        '404':
          description: Returned when category was not found
        '415':
          description: Returned on invalid Content-Type header
        '429':
          description: Exceeded requests limits
      operationId: get-catalog-category
      description: Returns the selected category. Max. 1x request(s) in 5 s period.
    parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/_format'
components:
  schemas: {}
  securitySchemes:
    API_KEY:
      type: http
      scheme: bearer
  parameters:
    _format:
      name: _format
      in: path
      required: true
      schema:
        enum:
          - json
          - xml
          - html
        example: json
        default: json
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    isoCode:
      name: isoCode
      in: query
      required: false
      schema:
        type: string
        default: de
        example: de
        description: The language of the returned data
    accept:
      name: accept
      in: header
      required: false
      schema:
        type: string
        default: application/json
  responses:
    '200':
      description: Returned when successful
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
security:
  - API_KEY: []
