openapi: 3.0.0
info:
  title: BigBuy
  version: v202102
  description: 'OpenAPI spefication to interact with bigbuy.eu'
servers:
  - url: 'https://api.bigbuy.eu'
    description: Production endpoint
  - url: 'https://api.sandbox.bigbuy.eu'
    description: Sandbox endpoint
paths:
  '/rest/catalog/categories.{_format}':
    $ref: "./resources/catalog/categories/categories.yaml"
  '/rest/catalog/categories/{id}.{_format}':
    $ref: "./resources/catalog/categories/category-by-id.yaml"
components:
  schemas: {}
  securitySchemes:
    API_KEY:
      type: http
      scheme: bearer
security:
  - API_KEY: []