openapi: 3.0.0
info:
  title: BigBuy
  version: v202102
  description: ''
servers:
  - url: 'https://api.bigbuy.eu/'
    description: Production endpoint
  - url: 'https://api.sandbox.bigbuy.eu/'
    description: Sandbox endpoint
paths:
  $ref: './resources/categories.yaml'
 
components:
  schemas: {}
  securitySchemes:
    API_KEY:
      type: http
      scheme: bearer
security:
  - API_KEY: []
